### ISSUE TITLE
Pipeline advances to "next" even if "setup" requires an input that is never generated.

### ISSUE THREAD

**Issue by jrs65** [radiocosmology/caput#152]
Mostly in the title. It seems to me from my read through of some pipeline issues that if a task takes an argument for setup, and then more inputs for it's next, even if the required setup inputs aren't generated, the next will still eventually get called for it's arguments. This tends to break pipeline tasks as they don't assume they could be in this state. The correct behaviour would be to have the pipeline task finish immediately as soon as it realises it's never getting it's setup input.

@nritsche @anjakefala I've tagged one of you both in here, but we can figure out where to actually assign it later this week.

**Comment by nritsche** [comment]
Do you have an example config for this by any chance?

**Comment by jrs65** [comment]
Yes. But not a short one.

Here's the relevant section cut out of the daily config:
```
    # Mask out intercylinder baselines before beam forming to minimise cross
    # talk. This creates a copy of the input that shares the vis dataset (but
    # with a distinct weight dataset) to save memory
    - type: draco.analysis.flagging.MaskBaselines
      requires: manager
      in: sstream
      out: sstream_inter
      params:
        share: vis
        mask_short_ew: 1.0

    # Load the source catalogs to measure fluxes of
    - type: draco.core.io.LoadBasicCont
      out: source_catalog
      params:
        files:
        - "/project/rpp-krs/chime/chime_processed/catalogs/ps_cora_10Jy.h5"
        - "/project/rpp-krs/chime/chime_processed/catalogs/ps_CGRaBS.h5"
        - "/project/rpp-krs/chime/chime_processed/catalogs/ps_QSO_05Jy.h5"

    # Measure the observed fluxes of the point sources in the catalogs
    - type: draco.analysis.beamform.BeamFormCat
      requires: [manager, sstream_inter]
      in: source_catalog
      params:
        timetrack: 60.0
        save: true
        output_name: "sourceflux_{tag}.h5"
```

The issue is the BeamFormCat task. It can happen that no `sstream_inter` is ever produced (i.e. if there wasn't any good data to generate it). In that case the `.setup()` for the task doesn't seem to get run, but it will still advance the state and attempt to call the `.process()` for the task, which fails because `.setup()` never generated some required state.
